### ISSUE TITLE
Feature Request: Support for multiple AND matching criteria

### ISSUE THREAD

**Issue by cameronmoreau** [thales-e-security/envoy#18]
There is a use case in the Istio Community where users would like multiple `AND`'d criteria requirements when matching to an IDP.

I believe that we may not need to worry about an `OR` case right now for MVP.

Example of proposed `oidc_filter` config with several `AND`'d match criteria. The following example uses [envoy's attribute criteria - authority and query match](https://www.envoyproxy.io/docs/envoy/latest/api-v2/service/auth/v2/attribute_context.proto.html?highlight=query)
```yaml
config:
  matches:
    tenant1.acme.com:
      idp:
        ...
        criteria:
          - header: :authority
            value: "tenant.cluster.com:8443"
          - header: :query
            value: "idp=google"
```
