### ISSUE TITLE
Feature Request: Allows “inline_jwks” string

### ISSUE THREAD

**Issue by cameronmoreau** [thales-e-security/envoy#19]
[Envoy's jwt_authn_filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/jwt_authn_filter#inline-jwks-config-example) allows the ability to inline a jwks public key.

This functionality would allow Istio to manage jwks public keys, as this approach is more inlined with the [Istio authn policy](https://istio.io/docs/tasks/security/authn-policy/) setup today.

The following examples include the two proposed jwks uri schemas. They specifically follow the same format of the [jwt_authn_filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/jwt_authn_filter#inline-jwks-config-example)

An `oidc_filter` would require one of `remote_jwks` or `local_jwks` to be set.

**Example using remote_jwks:**
```yaml
config:
  matches:
    tenant1.acme.com:
      idp:
        ...
        remote_jwks:
          http_uri:
            uri: https://www.googleapis.com/oauth2/v3/certs
            cluster: idp-api-cluster
```

**Example using local_jwks:**
```yaml
config:
  matches:
    tenant1.acme.com:
      idp:
        ...
        local_jwks:
          inline_string: PUBLIC-KEY
```
