### ISSUE TITLE
Feature Request: Add “issuer” field to perform jwt issuer check

### ISSUE THREAD

**Issue by cameronmoreau** [thales-e-security/envoy#20]
An Istio community member mentioned that the [issuer field](https://openid.net/specs/openid-connect-core-1_0.html#IssuerIdentifier) must be validated when verifying a JWT as per the OpenID Connect Spec. It appears that the [envoy jwt_auth_filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/jwt_authn_filter#jwtprovider) supports the issuer field as well.

Example of the proposed `oidc_filter` config
```yaml
config:
  matches:
    tenant1.acme.com:
      idp:
        ...
        issuer: "accounts.google.com"
```
